define([], function() {
    tutorialScript = [
        ['say', 'Apretá en cualquier lado para parar la demo.', 'Press anywhere to stop the demo.', 7000],
        ['wait', 500],
        ['pressRadio', 'radio-layout', 'sequence'],
        ['pressRadio', 'radio-number-of-frames', '7'],
        ['wait', 100],
        ['press', 'next-frame'],
        ['drag', 'next-frame', 0.3],
        ['wait', 8000],
        ['say', 'La animación se hace con...', 'Animation is made of...', 5000],
        ['wait', 6000],
        ['say', '...muchos dibujos.', '...lot of drawings.', 5000],
        ['release', 'next-frame'],
        ['wait', 800],
        ['press', 'prev-frame'],
        ['drag', 'prev-frame', 0.3],
        ['wait', 3000],
        ['release', 'prev-frame'],
        ['wait', 800],
        ['press', 'next-frame'],
        ['drag', 'next-frame', 0.3],
        ['wait', 2000],
        ['say', 'El chiste está en pasarlos rápido.', 'The thing is, you have to pass them fast.', 8000],
        ['drag', 'next-frame', 0.3, 1.0, 10000],
        ['wait', 2000],
        ['say', 'Muy rápido.', 'Very fast.', 3000],
        ['wait', 4000],
        ['say', 'Tan rápido que engaña a los ojos.', 'So fast it cheats the eyes.', 5000],
        ['wait', 3000],
        ['drag', 'next-frame', 1.0, 0.3, 5000],
        ['release', 'next-frame'],
        ['wait', 1000],
        ['say', 'Hay varias formas de lograr esto en la realidad.', 'There are several ways to archieve this in the reality.', 5000],
        ['wait', 2000],
        ['pressRadio', 'radio-layout', 'zoetrope'],
        ['wait', 800],
        ['press', 'next-frame'],
        ['drag', 'next-frame', 0.1, 0.5, 5000],
        ['say', 'Esto se denomina zoótropo.', 'This is called a Zoetrope.', 5000],
        ['drag', 'next-frame', 0.5, 1.0, 5000],
        ['wait', 5000],
        ['drag', 'next-frame', 1.0, 0.1, 2000],
        ['release', 'next-frame'],
        ['wait', 1500],
        ['pressRadio', 'radio-layout', 'stack'],
        ['say', 'Para dibujar animación, es útil transparentar las hojas.', 'To draw animation, having the sheets transparent is useful.', 8000],
        ['wait', 3000],
        ['press', 'opacity'],
        ['drag', 'opacity', 0.9, 0.1, 2000],
        ['drag', 'opacity', 0.1, 0.4, 2000],
        ['drag', 'opacity', 0.4, 0.1, 2000],
        ['release', 'opacity'],
        ['wait', 800],
        ['press', 'next-frame'],
        ['drag', 'next-frame', 0.9],
        ['wait', 4000],
        ['say', 'Para tener una referencia de lo anterior.', 'So you have a reference of the previous.', 8000],
        ['wait', 8000],
        ['release', 'next-frame'],
        ['wait', 1000],
        ['pressRadio', 'radio-layout', 'lightbox'],
        ['wait', 1500],
        ['say', 'Esto es un flipbook.', 'This is a Flipbook.', 4000],
        ['wait', 1500],
        ['press', 'next-frame'],
        ['drag', 'next-frame', 0.3],
        ['wait', 1500],
        ['release', 'next-frame'],
        ['wait', 2000],
        ['say', '¿Ves el dibujo anterior abajo?', 'See the previous drawing below?', 4000],
        ['wait', 2000],
        ['press', 'prev-frame'],
        ['drag', 'prev-frame', 0.3],
        ['wait', 3000],
        ['release', 'prev-frame'],
        ['say', 'Podés dibujar acá adentro. ¡Probalo ahora!', 'You can draw inside. Try it now!', 5000],
        ['wait', 6000],
        ['say', 'Nos vemos.', 'Bye.', 3000],
        ['wait', 4000],
    ];

    return tutorialScript;
});
